DATASET_NAME = "Spotify"
SCHEMA_NAME = "raw"

SPOTIFY_TRACK_COLUMNS = ['ID', 'ALBUM_ID', 'ANALYSIS_URL', 'ARTISTS_ID', 'AVAILABLE_MARKETS', 'COUNTRY', 'HREF', 'LYRICS', 
                        'NAME', 'PLAYLIST', 'PREVIEW_URL', 'TRACK_HREF', 'TRACK_NAME_PREV', 'TRACK_NUMBER', 'URI', 'TYPE']


SPOTIFY_TRACK_METRICS_COLUMNS = ['ID', 'ACOUSTICNESS', 'DANCEABILITY', 'DISC_NUMBER', 'DURATION_MS', 'ENERGY', 'INSTRUMENTALNESS', 
                                 'KEY', 'LIVENESS', 'LOUDNESS', 'MODE', 'POPULARITY', 'SPEECHINESS', 'TEMPO', 'TIME_SIGNATURE', 'VALENCE']
